Refactor code

diff --git a/wifi-password b/wifi-password
--- a/wifi-password
+++ b/wifi-password
@@ -17,49 +17,6 @@ Examples:
 EOS
 }
 
-# Get the operating system type
-getOS() {
-  case "`uname -s`" in
-    Darwin)
-      OS_NAME='osx'
-    ;;
-    Linux)
-      OS_NAME='linux'
-    ;;
-    CYGWIN* | MINGW* | MSYS*)
-      OS_NAME='windows'
-    ;;
-    *)
-      OS_NAME='unknown'
-    ;;
-  esac
-}
-
-getPassword() {
-  case ${OS_NAME} in
-    osx)
-      # Run command
-      cmdOutput="`security find-generic-password -D 'AirPort network password' -a "${option_i}" -g 2>&1 >/dev/null`"
-
-      # exit if ssid not found
-      if [[ ${cmdOutput} =~ "could" ]]; then
-        echo >&2 "ERROR: Could not find SSID \"${option_i}\""
-        exit 1
-      fi
-
-      # Extract password from string
-      wifiPassword=$(echo ${cmdOutput}| cut -d'"' -f 2)
-      echo ${wifiPassword}
-    ;;
-    linux)
-      echo "linux"
-    ;;
-    windows)
-      echo "windows"
-    ;;
-  esac
-}
-
 # Main script
 if [[ $# -eq 0 ]]; then
   usage
@@ -100,6 +57,29 @@ if [[ ${option_v} ]]; then
 fi
 
 if [[ -n ${option_i} ]]; then
-  getOS
-  getPassword
+  case "`uname -s`" in
+    Darwin)
+    # Run command
+      cmdOutput="`security find-generic-password -D 'AirPort network password' -a "${option_i}" -g 2>&1 > /dev/null`"
+
+      # exit if ssid not found
+      if [[ ${cmdOutput} =~ "could" ]]; then
+        echo >&2 "ERROR: Could not find SSID \"${option_i}\""
+        exit 1
+      fi
+
+      # Extract password from string
+      wifiPassword=$(echo ${cmdOutput} | cut -d'"' -f 2)
+      echo ${wifiPassword}
+    ;;
+    Linux)
+      OS_NAME='linux'
+    ;;
+    CYGWIN* | MINGW* | MSYS*)
+      OS_NAME='windows'
+    ;;
+    *)
+      OS_NAME='unknown'
+    ;;
+  esac
 fi
