Minor fixes

diff --git a/wifi-password b/wifi-password
--- a/wifi-password
+++ b/wifi-password
@@ -6,42 +6,57 @@ version="0.1.0"
 function usage() {
   cat << EOS
 Usage:
-  wifi-password [options] [network-name]
+  wifi-password [options]
 Options:
-  -v, --version    Output version
-  -h, --help       Show the usage.
+  -i      - SSID of the network you want to get the password
+  -a      - Get the list of all network with their passwords
+  -v      - Output version
+  -h      - Show the usage
 Examples:
-  wifi-password foo-network
+  wifi-password -i foo-network
 EOS
 }
 
 getOS() {
   case "`uname -s`" in
     Darwin)
-      OS_NAME='osx' ;;
+      OS_NAME='osx'
+    ;;
     Linux)
-      OS_NAME='linux' ;;
+      OS_NAME='linux'
+    ;;
     CYGWIN* | MINGW* | MSYS*)
-      OS_NAME='windows' ;;
+      OS_NAME='windows'
+    ;;
     *)
-      OS_NAME='unknown' ;;
+      OS_NAME='unknown'
+    ;;
   esac
 }
 
-case $1 in
-  -V | --version)
-    echo ${version}
-    exit
-  ;;
-  -h | --help)
-    usage
-    exit
-  ;;
-  *)
-    usage
-    exit
-  ;;
-esac
+while getopts "hiv" opt; do
+  case ${opt} in
+    h | i | v)
+      declare option_${opt}=${OPTARG:-0}
+    ;;
+    \?)
+      echo >&2 "Use 'wifi-password -h' to see usage info"
+      exit 1
+    ;;
+  esac
+done
 
-getOS
-echo ${OS_NAME}
+shift $((OPTIND-1))
+
+# If number of arguments is 0 then exit
+if [[ $# -gt 0 ]]; then
+  echo >&2 "Invalid arguments: $@"
+  echo >&2 "Use 'wifi-password -h' to see usage info"
+  exit 1
+fi
+
+# Main script
+if [[ ${option_h} ]]; then
+  usage
+  exit 0
+fi
