Ouput colorized errors

diff --git a/wifi-password b/wifi-password
--- a/wifi-password
+++ b/wifi-password
@@ -103,7 +103,7 @@ if [[ -n ${option_i} ]]; then
       cmdOutput="`security find-generic-password -D 'AirPort network password' -a "${option_i}" -g 2>&1 > /dev/null`"
       # exit if ssid not found
       if [[ ${cmdOutput} =~ "could" ]]; then
-        echo >&2 "ERROR: Could not find SSID \"${option_i}\""
+        echo >&2 "\n${RED}ERROR:${NORMAL} Could not find SSID \"${option_i}\""
         exit 1
       fi
       # Extract password from string
@@ -121,7 +121,7 @@ if [[ -n ${option_i} ]]; then
       echo ${wifiPassword}
     ;;
     *)
-      echo >&2 "Operating system is unknown"
+      echo >&2 "\n${RED}Error:${NORMAL} Operating system is unknown"
       exit 1
     ;;
   esac
