Get password for osx

diff --git a/wifi-password b/wifi-password
--- a/wifi-password
+++ b/wifi-password
@@ -38,7 +38,18 @@ getOS() {
 getPassword() {
   case ${OS_NAME} in
     osx)
-      osx_command=$(printf "sudo security find-generic-password -D 'AirPort network password' -a '%s' -g" "${option_i}")
+      # Run command
+      cmdOutput="`security find-generic-password -D 'AirPort network password' -a "${option_i}" -g 2>&1 >/dev/null`"
+
+      # exit if ssid not found
+      if [[ ${cmdOutput} =~ "could" ]]; then
+        echo >&2 "ERROR: Could not find SSID \"${option_i}\""
+        exit 1
+      fi
+
+      # Extract password from string
+      wifiPassword=$(echo ${cmdOutput}| cut -d'"' -f 2)
+      echo ${wifiPassword}
     ;;
     linux)
       echo "linux"
